
package com.ipartek.formacion.ejemplojaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraImpl", targetNamespace = "http://ejemplojaxws.formacion.ipartek.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://ejemplojaxws.formacion.ipartek.com/", className = "com.ipartek.formacion.ejemplojaxws.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://ejemplojaxws.formacion.ipartek.com/", className = "com.ipartek.formacion.ejemplojaxws.SumarResponse")
    @Action(input = "http://ejemplojaxws.formacion.ipartek.com/CalculadoraImpl/sumarRequest", output = "http://ejemplojaxws.formacion.ipartek.com/CalculadoraImpl/sumarResponse")
    public int sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
